<a href="https://colab.research.google.com/github/RemyaDeepesh/executive_program_AI_ML_python_pgm/blob/main/sales_data_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Matrix Operations for Business Data

In [ ]:

import numpy as np

# Sales data for 3 products across 4 regions
sales_matrix = np.array([
    [120, 140, 130, 150],  # Product 1
    [80, 90, 100, 95],      # Product 2
    [200, 210, 190, 205]    # Product 3
])

print("Sales Matrix:")
print(sales_matrix)
print("" + "="*50 + "")

# Task 1: Find total sales per product
total_sales_per_product = sales_matrix.sum(axis=1)
print("Task 1: Total Sales per Product")
print(f"Product 1: {total_sales_per_product[0]}")
print(f"Product 2: {total_sales_per_product[1]}")
print(f"Product 3: {total_sales_per_product[2]}")
print("" + "="*50 + "")

# Task 2: Find total sales per region
total_sales_per_region = sales_matrix.sum(axis=0)
print("Task 2: Total Sales per Region")
print(f"Region 1: {total_sales_per_region[0]}")
print(f"Region 2: {total_sales_per_region[1]}")
print(f"Region 3: {total_sales_per_region[2]}")
print(f"Region 4: {total_sales_per_region[3]}")
print("" + "="*50 + "")

# Task 3: Identify the best performing product
best_product_index = total_sales_per_product.argmax()
best_product_sales = total_sales_per_product[best_product_index]
print("Task 3: Best Performing Product")
print(f"Product {best_product_index + 1} with total sales: {best_product_sales}")
print("" + "="*50 + "")

# Task 4: Identify the region with highest sales
best_region_index = total_sales_per_region.argmax()
best_region_sales = total_sales_per_region[best_region_index]
print("Task 4: Region with Highest Sales")
print(f"Region {best_region_index + 1} with total sales: {best_region_sales}")



Sales Matrix:
[[120 140 130 150]
 [ 80  90 100  95]
 [200 210 190 205]]
Task 1: Total Sales per Product
Product 1: 540
Product 2: 365
Product 3: 805
Task 2: Total Sales per Region
Region 1: 400
Region 2: 440
Region 3: 420
Region 4: 450
Task 3: Best Performing Product
Product 3 with total sales: 805
Task 4: Region with Highest Sales
Region 4 with total sales: 450
